### ISSUE TITLE
Hang on exit

### ISSUE THREAD

**Issue by tschundler** [TheMariday/marimapper#49] opened 2024-12-16 04:05 UTC
after ~5 camera positions 3D mapping, I selected "n" to finish scanning, and the program hang. I thought maybe it was finishing up some processing.  ` led_map_3d.csv` seems fine though. After several minutes, I interrupted it. Here's the trace if that's useful.

```
[ERROR/DetectorProcess-1] failed to set camera gain to -1
Capturing sequence: 100%|██████████████████████████████████████████████████████████████████████████████| 300/300 [02:17<00:00,  2.18LEDs/s][ERROR/DetectorProcess-1] failed to set camera gain to -1

[ERROR/DetectorProcess-1] Failed to set exposure to -1
[ERROR/DetectorProcess-1] Failed to set exposure to -1
Start scan? [y/n]: n
Exiting Marimapper

^CProcess SFM-2:
Traceback (most recent call last):
  File "/opt/src/marimapper/.venv/bin/marimapper", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/src/marimapper/marimapper/scripts/scanner_cli.py", line 73, in main
    scanner.close()
  File "/opt/src/marimapper/marimapper/scanner.py", line 83, in close
    self.sfm.join()
  File "/usr/lib/python3.11/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/popen_fork.py", line 43, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/process.py", line 317, in _bootstrap
    util._exit_function()
  File "/usr/lib/python3.11/multiprocessing/util.py", line 363, in _exit_function
    _run_finalizers()
  File "/usr/lib/python3.11/multiprocessing/util.py", line 303, in _run_finalizers
    finalizer()
  File "/usr/lib/python3.11/multiprocessing/util.py", line 227, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/queues.py", line 199, in _finalize_join
    thread.join()
  File "/usr/lib/python3.11/threading.py", line 1119, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.11/threading.py", line 1139, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

(.venv) ted@pocket3:/opt/src/marimapper$
```

**Comment by TheMariday** [comment] 2024-12-16 04:32
Hi there @tschundler

Thank you so much for the bug report! I have encountered this as well.

It's todo with how multiprocessing cleans up (or fails to) and leaves queues waiting to clear.

I thought I'd managed to fix it but hey ho!

Did you manually close any of the windows before or during the hang?

Thank you!

**Comment by tschundler** [comment] 2024-12-16 05:03
I don't think I closed either of the windows. If I did, it was after the hang.

**Comment by TheMariday** [comment] 2024-12-16 05:05
I'll have a look into this this week, it looks like you're using a Linux distro?

Either way, it should be safe to Ctrl-C after the 3d map csv has been updated.

**Comment by tschundler** [comment] 2024-12-16 05:46
Yeah. OpenCV wouldn't build on my Mac - rather than debug it, I tried on Linux and it built fine immediately.

**Comment by TheMariday** [comment] 2024-12-23 17:37
Believe it or not, I think this is caused by the same underlying issue that caused #46

Should be fixed soon.

**Closed** 2024-12-27 12:20 UTC
Labels: bug

**Comment by TheMariday** [comment] 2024-12-27 12:24
This should be much improved in v2.3 which can be grabbed with `pipx upgrade marimapper`

Happy to reopen this if the issue is still persisting
