### ISSUE TITLE
The number of mapped LEDs sometimes goes down after adding a scan 

### ISSUE THREAD

**Issue by Robotmad** [TheMariday/marimapper#37] opened 2024-12-06 16:13 UTC
Trying to 100% map 1000 LEDs on an xmas tree, marimapper is generally fantastic, instructions were great, but sometimes I line up a camera view to try to cover some missing LEDs but then find that others which were previously known lose their co-ordinates.  Do you have any understanding of what can cause this to happen - perhaps the new view introduces too much variation (doubt) in the location of the LED that it fails to meet a criteria.  I've looked for confidence thresholds but not found anything to try adjusting.

**Comment by TheMariday** [comment] 2024-12-06 16:27
Hi there! Thank you so much for the complements and feedback!

My apologies that you've hit this, good news is I think I know what's going on here, bad news is I don't have a simple fix yet.

Marimapper works on parameter optimisation based on the LED positions detected. Each LED scanned adds to that optimisation space.

The optimisation may degrade, even with more points, if the points are erroneous or cause the optimiser to get stuck in a local minima.

Howeverrrrrr, I might be completely wrong and it's just an uncaught bug somewhere.

I have seen this once or twice myself when edge case testing but it was hard to replicate.

I will look into this tonight, see if I can replicate it again and get back to you with a fix.

My initial thought is to put in a quick check to throw an error to the user and disregard the last set of detections if the reconstructed LED count decreases.

In the mean time, you can remove the points of the last scan that caused the degredation by closing Marimapper, deleting the last scan csv file, then re-opening it in the same directory.

I hope this helps and thank you for the feedback.

**Comment by Robotmad** [comment] 2024-12-06 17:27
Hi - very impressed how quickly you've responded - in fact I think I've found and solved the issue - the gap filling algorithm will only fill gaps of MORE THAN 1 LED - so as I added more views my gaps got smaller and then stopped being filled in.  I'll try to make a PR with the fix.

**Comment by TheMariday** [comment] 2024-12-06 18:43
Thank you for the PR! I assume it's working as intended now?

I'll still raise an issue for the optimisation problem.

It's so nice to hear people are using the tool and please do drop me a line if you have any further comments or questions.

**Comment by Robotmad** [comment] 2024-12-07 11:15
Yes all good now - 1000 LEDs mapped - now working on controlling them in fun and interesting ways.  To aid in coming up with camera positions to tick off the hard to view LEDs I added a feature to illuminate all those that were not yet mapped before asking the user to confirm to start the next scan - it worked but I don't think it was an optimal solution.  I found it hard to get a list of known (and hence work out the missing) LEDs - resorted to reading back in the 3d led map file, but I'm sure there must be a way to access this information direct from the sfm process.  I needed get this display to wait until all of the processing on startup or from the last scan was complete and the file updated - had to check that none of the queues still had anything waiting to be processed and that the sfm process wasn't working on any data - which all seemed overly complicated.

**Comment by TheMariday** [comment] 2024-12-07 14:36
That's a fantastic feature!

I'm sorry the queues caused you a headache, they were sadly a last resort due to Open3D and OpenCV not being able to run in a thread whilst also allowing some terminal input.

I've got a few new features in mind for Marimapper that require colour, so now seems to be a good time to upgrade the back-ends to be able to receive a full buffer instead of just an led_id and a status.

This should allow the colouration you've developed as well as faster RGB based led indexing.

I'll also add in a feedback loop queue to allow the reconstructor to pipe led info to the backend so they can be coloured whilst in-between scans.

I'm thinking


| Colour | Detected | Position found | State
|--------|------------|-----------------|----------|
| 🟢| **Yes**           | **Yes**                   | LED Good |
| 🔵 | No            | **Yes**                   | LED interpolated |
| 🟠| **Yes**           | No                 | LED detected but can't localise |
| 🔴    | No           | No                     | LED not detected or localised |

I'm glad you got all your LEDs scanned and thank you so much for reaching out! It really means a lot to me that my work is helping someone :D

**Closed** 2024-12-09 16:21 UTC
Labels: bug, improvement
