### ISSUE TITLE
Suggestion: Report when waiting for darkness

### ISSUE THREAD

**Issue by tschundler** [TheMariday/marimapper#50] opened 2024-12-16 06:22 UTC
When I first ran this, it seemed stuck. I tried both Pixelblaze & WLED with no luck. So I dug into the code, and added some output to try to diagnose the problem, and quickly realized - it doesn't take a reference frame and a bright spot at the edge of my binds was confusing it.

Pending #33, I think it would help to let the user know when it is waiting for a dark frame. eg something like

```
--- a/marimapper/detector.py
+++ b/marimapper/detector.py
@@ -128,10 +128,13 @@ def enable_and_find_led(
     led = LED2D(led_id, view_id)

     if led_backend is None:
+        print("backend is unset")
         return led

     # First wait for no leds to be visible
     while find_led(cam, threshold, display) is not None:
+        print("Waiting for no LEDs to be visible. Check the preview. Does the environment need to be darker?")
+        time.sleep(0.1)
         pass

     # Set the led to on and start the clock
```

**Comment by TheMariday** [comment] 2024-12-16 09:39
This is actually a duplicate of https://github.com/TheMariday/marimapper/issues/32

However this is written better so keeping it!

This used to be a feature actually but it got removed in the v2 version.

Thank you for raising it!

**Comment by TheMariday** [comment] 2024-12-16 20:22
The backend is none warning should be caught by this line in the scanner.py file:
```
 if len(self.led_id_range) == 0:
    print(
        "LED range is zero, have you chosen a backend with 'marimapper --backend'?"
    )
    continue
```

Adding a warning to the user that there are leds lit without over-warning them is going to be tricky. I'm going to adjust how the queues work that should make it a bit easier but yes, working on this but a bit harder than planned.

New queue system requests a range of leds instead of a stream of id's. This will also make #38 easier to integrate

**Comment by tschundler** [comment] 2024-12-17 01:21
Is over-warning really a problem? It is text on a CLI rather than an `alert()`
You could show the warning again only if some time has passed (eg max every few seconds)

**Comment by TheMariday** [comment] 2024-12-17 21:17
I've got an idea as to how to implement this in a nice way, I'll keep you posted.

The reason it's tricky is just the structure of the code at the moment isn't conducive to this kind of warning, so it's time to refactor!

The only way the detector differentiates between being in detection mode or being in preview mode is whether the detection input queue has any elements in which isn't a good way to switch between two modes of operation.

I think I will move it to a more explicit switch so that we can add checks and background removal etc etc to the proecss.

Should make start / stop events easier to add.

**Comment by tschundler** [comment] 2024-12-27 05:25
Testing out the change:

```

Start scan? [y/n]: y
Capturing sequence:   0%|                                                           | 0/289 [00:00<?, ?LEDs/s][ERROR/DetectorProcess-1] Failed to set autofocus to 0
[ERROR/DetectorProcess-1] Failed to set autofocus to 0
[ERROR/DetectorProcess-1] Failed to set focus to 0
[ERROR/DetectorProcess-1] Failed to set focus to 0
[ERROR/DetectorProcess-1] Failed to put camera into manual exposure mode 0
[ERROR/DetectorProcess-1] Failed to put camera into manual exposure mode 0
[ERROR/DetectorProcess-1] failed to set camera gain to 0
[ERROR/DetectorProcess-1] failed to set camera gain to 0
[ERROR/DetectorProcess-1] Failed to set exposure to -10
[ERROR/DetectorProcess-1] Failed to set exposure to -10
[ERROR/DetectorProcess-1] Detector process can detect an LED when no LEDs should be visible
[ERROR/DetectorProcess-1] Detector process can detect an LED when no LEDs should be visible
[ERROR/DetectorProcess-1] Failed to set autofocus to -1
[ERROR/DetectorProcess-1] Failed to set autofocus to -1
[ERROR/DetectorProcess-1] Failed to set focus to -1
[ERROR/DetectorProcess-1] Failed to set focus to -1
[ERROR/MainProcess] Scan failed
Capturing sequence:   0%|                                                           | 0/289 [00:03<?, ?LEDs/s]
Start scan? [y/n]:
```

it seems everything is logged twice. Also, the reason it didn't start is lost in messages about unable to set camera properties. (shouldn't it set those properties before looking for LEDs?)

I was actually confused the first time and though I didn't press "y" and maybe hit another letter instead that it was asking again to start.

**Comment by TheMariday** [comment] 2024-12-27 06:49
That's really interesting! I haven't seen things log twice before like this! I'll have an investigate.

I'll also try and put the camera into dark mode prior to the scan starting to raise any of these errors early.

I'll also try and combine them into one or two lines so it's less overwhelming.

Glad the feature works though!

**Closed** 2024-12-27 12:20 UTC
Labels: improvement

**Comment by TheMariday** [comment] 2024-12-27 12:23
This should be much improved in v2.3 which can be grabbed with `pipx upgrade marimapper`

Happy to reopen this if the issue is still persisting
